version: v1
model: rexnet200_BCE
fold: 1
save_root: dump
csv_path: data/fold/ver1/train-jpegs-512/train.csv
img_dir: data/npz/train-jpegs-512
ckpt_path: ## Write path to the fold-1 backbone trained with BCE ##
# example)
# ckpt_path: wandb/run-20201020_060628-2cpwvzq3/files/checkpoints/epoch=01-val_loss=0.095.ckpt
n_workers: 8
gpu: 0
image_size: 512
chunk_size: 16